### PR TITLE
Add function to get multiple games pbp from nba api

### PR DESCRIPTION
**Pull request by papagorgio23**
It was annoying to get play by play data one game at a time. I added a function to date in many game ids and return all the pbp together. 

I also cleaned up the pbp function to rename columns and add additional info.

### CODE REVIEW

**Review by saiemgilani — CHANGES_REQUESTED** [review]
So, this makes sense, but I'm gonna ask one of us to re-write it to use progressr (using our ```progressively()``` function) and instead of a parameter for return message, people can subscribe to updates by wrapping it with progressr with default behavior being silent except for warnings/errors. The idea is sound though. We need a macro function that combines with one of the boxscore functions to get lineups added to the tibble before we start purrring it imo. Cause otherwise that function isn't really a value add, you're just doing something users should be able to do themselves (in an ideal world)

**Comment by papagorgio23** [comment]
Don’t worry lineups are coming. This is just the first step. I’ll change to progressively and remove the message

**Comment by papagorgio23** [comment]
should be good now

**Comment by saiemgilani** [comment]
I'll want to double check locally but looks right

**Comment by papagorgio23** [comment]
forgot to re-run check but now everything is final. Next PR will be to fix the game logs

**Comment by saiemgilani** [comment]
Yah I will merge in a bit

**Pull request merged**
